version: '2.2'

services:
  mongo:
    image: mongo
    volumes:
      - ./.mongo-data:/data/db
    restart: always

  app:
    image: ghcr.io/invakid404/invapaste:latest
    ports:
      - 3000:3000
    environment:
      MONGO_URI: 'mongodb://mongo:27017/invapaste'
    depends_on:
      - mongo
    restart: always
