on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn build
